name: mobile

description: A Flutter application with offline map capabilities.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^10.1.0
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  flutter_image_compress: ^2.3.0
  shared_preferences: ^2.3.4
  flutter_riverpod: ^2.6.1
  mapbox_maps_flutter: ^2.5.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  android_intent_plus: ^5.2.1
  cupertino_icons: ^1.0.8
  # internet_connection_checker: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  patrol: ^3.13.2

flutter:
  uses-material-design: true